name: Auto Pull Request

on:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'   # excludes master

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create release pr
        run: gh pr create -B "main" -t "Develop ${{env.BRANCH}}" -b ""
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: "${GITHUB_REF#refs/heads/}"
