name: Auto Pull Request

on:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'   # excludes master
    branch_protection_rule:
      types: edited

jobs:
  Auto_Pull_Request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create release pr
        run: gh pr create -B "main" -t "Develop ${{ env.BRANCH }} into main" -b "" -a $AUTHOR -r $AUTHOR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${GITHUB_REF#refs/heads/}
          ASSIGNEE: ${{ github.event.pull_request.user.login }}
          AUTHOR: ${{ github.event.pusher.name }}
