name: Manual Deploy

on:
  push:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: check diff file name
        run: |
          echo $RANDOM
          A=$(echo $RANDOM)
          echo $A