name: Manual Deploy

on:
  push:
    branches:
      - 'dev-**'        # matches every branch

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: check diff file name
        run: |
          sh ./sample_action.sh
          