name: Manual Deploy

on:
  push:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: check diff file name
        run: |
          echo $(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1 | sort | uniq)