name: Auto Pull Request

on:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'   # excludes master

jobs: 
  Auto_Pull_Request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create release pr
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          git branch -a
          if [ -z "$(git diff origin/main --diff-filter=ACMR --name-only)" ]; then
            exit 0
          fi
          gh pr create -B "main" -t "Develop ${{ env.BRANCH }} into main" -b "" -a $AUTHOR -r--e $AUTHOR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${GITHUB_REF#refs/heads/}
          ASSIGNEE: ${{ github.event.pull_request.user.login }}
          AUTHOR: ${{ github.event.pusher.name }}
