name: cloc test

on:
  push:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: cloc test
        run: |
          sudo apt install cloc
          cloc ./

          