name: Auto Pull Request

on:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'   # excludes master

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create pull request
        run: |
          hub push
          hub pull-request -b main -m "Release ${{ GITHUB_REF#refs/heads/ }}"