name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: "Deploy target ${{ secrets.DEPLOYMENT_LOCK }}"
        options: 
        - ${{ secrets.DEPLOYMENT_LOCK }}
      message:
        required: true
        default: "Write some messsage here"
      dryrun:
        type: boolean
        description: Is dryrun?
        default: true
      environment:
        type: environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Show inputs
      run: |
        echo "GITHUB_REF#refs/heads/                    = ${GITHUB_REF#refs/heads/}"
        echo "target: ${{ github.event.inputs.branch }}"
        echo "target: ${{ github.event.inputs.target }}"
        echo "message: ${{ github.event.inputs.message }}"
        echo "dryrun: ${{ github.event.inputs.dryrun }}"
