name: test CI workflow

on:
  push:
    branches:
      - 'sub**'        # match the branch started with pkg-

jobs:
  Test_checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git config --global credential.helper cache
          git config -l
          git clone -b master https://nakanoasato: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@github.com/GembaCPS/ProcessVisualizer.git --recursive
          ls ProcessVisualizer
          ls ProcessVisualizer/view/public/html/AreaSettingUI
    

  Auto_Pull_Request:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64

      - uses: actions/checkout@v3
      - name: Create pull request
        continue-on-error: true
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          if [ -z "$(git diff origin/main --diff-filter=ACMR --name-only)" ]; then
            echo "At new branch. Dont create pr"
            exit 0
          fi
          gh pr create -B "main" -t "Develop ${{ env.BRANCH }} into main" -b "" -a $AUTHOR -r $AUTHOR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${GITHUB_REF#refs/heads/}
          ASSIGNEE: ${{ github.event.pull_request.user.login }}
          AUTHOR: ${{ github.event.pusher.name }}
