name: Test CD

on:
  push:
    branches:
      - 'main'

jobs:
  Integration_Test:
    if: contains(github.event.head_commit.message, 'quick')
    runs-on: ubuntu-latest
    steps:
      - name: Check merged branch
        run: |
          dir="${{ github.event.head_commit.message }}";
          echo $dir
          if [[ $dir =~ "sub" ]]; then
            echo "contain quick"
            exit 0
          else
            echo "not contained"
          fi
      
      - name: 2nd proc
        run: |
          ls
