name: Test CD

on:
  push:
    branches:
      - 'main'

jobs:
  Integration_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check merged branch
        run: |
          resourceName=$(echo ${{ github.event.head_commit.message }})
          echo $resourceName
