name: Test CD

on:
  push:
    branches:
      - 'main'

jobs:
  Integration_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check merged branch
        run: |
          resourceName=${{ github.event.head_commit.message }}
          for dir in $resourceName;
          do
            echo $dir
