name: Test CD

on:
  push:
    branches:
      - 'main'

jobs:
  Integration_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check merged branch
        run: |
          dir="${{ github.event.head_commit.message }}";
          echo $dir
          if [ $dir =~ "quick-" ]; then
            echo "contain quick"
            exit 0
          else
            echo "not contained"
          fi
