name: Test CD

on:
  push:
    branches:
      - 'main'

jobs:
  Integration_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check merged branch
        run: |
          for dir in "${{ github.event.head_commit.message }}";
          do
            echo $dir
          done
